<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KPI Report - High Performers - Print</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 15mm;
        }
        body {
            font-family: 'Times New Roman', serif;
            font-size: 9pt;
            line-height: 1.3;
            color: #000;
            position: relative;
        }
        /* Watermark */
        body::after {
            content: "NCS Management Information System (MIS)";
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 28pt;
            font-weight: bold;
            color: #228B22; /* Forest Green color */
            opacity: 0.25;
            z-index: -1;
            pointer-events: none;
            white-space: nowrap;
            font-family: 'Times New Roman', serif;
            display: block;
            width: 80%;
            max-width: 80%;
            text-align: center;
        }
        @media print {
            body::after {
                opacity: 0.20;
                z-index: -1;
                font-size: 24pt;
                width: 70%;
                max-width: 70%;
            }
        }
        .restricted {
            text-align: center;
            font-weight: bold;
            font-size: 11pt;
            margin: 5px 0;
        }
        .restricted-header {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-weight: bold;
            font-size: 11pt;
            padding: 5px 0;
            background: white;
            z-index: 1000;
            display: none;
        }
        .restricted-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-weight: bold;
            font-size: 11pt;
            padding: 5px 0;
            background: white;
            z-index: 1000;
            display: none;
        }
        .header {
            text-align: center;
            margin-bottom: 10px;
        }
        .header h1 {
            font-size: 14pt;
            font-weight: bold;
            margin: 3px 0;
        }
        .header h2 {
            font-size: 12pt;
            font-weight: bold;
            margin: 3px 0;
        }
        .annex-info {
            text-align: right;
            font-size: 9pt;
            margin-bottom: 10px;
        }
        .filter-info {
            text-align: left;
            font-size: 9pt;
            margin-bottom: 10px;
            padding: 5px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
        }
        th {
            background-color: #f0f0f0;
            border: 1px solid #000;
            padding: 5px;
            text-align: center;
            font-weight: bold;
            font-size: 8pt;
        }
        td {
            border: 1px solid #000;
            padding: 4px;
            text-align: center;
            font-size: 8pt;
        }
        .sn-col { width: 5%; }
        .rank-col { width: 12%; }
        .name-col { width: 25%; }
        .service-col { width: 15%; }
        .command-col { width: 25%; }
        .score-col { width: 18%; }
        @media print {
            @page {
                margin-top: 20mm;
                margin-bottom: 20mm;
            }
            body {
                margin: 0;
                padding-top: 15mm;
                padding-bottom: 15mm;
            }
            .no-print {
                display: none;
            }
            .restricted-header,
            .restricted-footer {
                display: block;
            }
            .restricted:not(.restricted-header):not(.restricted-footer) {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print" style="text-align: center; margin-bottom: 20px; padding: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background: #007bff; color: white; border: none; border-radius: 5px;">
            Print Document
        </button>
    </div>

    <div class="restricted-header">RESTRICTED</div>
    <div class="restricted-footer">RESTRICTED</div>

    <div class="restricted">RESTRICTED</div>
    
    <div class="header">
        <h1>NIGERIA CUSTOMS SERVICE</h1>
        <h1>KEY PERFORMANCE INDICATOR (KPI) REPORT</h1>
        <h2>HIGH PERFORMERS - APER FORMS</h2>
        <h2>YEAR {{ $year }}</h2>
    </div>

    <div class="annex-info">
        <div>Generated: {{ date('d/m/Y') }}</div>
        <div>Generated By: {{ auth()->user()->email ?? 'N/A' }}</div>
    </div>

    <div class="filter-info">
        <strong>Filter Criteria:</strong><br>
        Score Range: {{ number_format($minScore, 2) }} - {{ number_format($maxScore, 2) }}<br>
        Total Officers: {{ count($kpiData) }}
    </div>

    <table>
        <thead>
            <tr>
                <th class="sn-col">S/N</th>
                <th class="rank-col">Rank</th>
                <th class="name-col">Name</th>
                <th class="service-col">Service No</th>
                <th class="command-col">Command</th>
                <th class="score-col">Performance Rating (HRD Score)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($kpiData as $row)
                <tr>
                    <td>{{ $row['serial_number'] }}</td>
                    <td>{{ $row['rank'] }}</td>
                    <td>{{ $row['name'] }}</td>
                    <td>{{ $row['service_number'] }}</td>
                    <td>{{ $row['command'] }}</td>
                    <td>{{ $row['hrd_score'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">
                        No officers found matching the specified criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>

