<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportTitle ?? 'Report' }} - Print</title>
    <style>
        @page {
            size: A4;
            margin: 20mm;
        }
        body {
            font-family: 'Times New Roman', serif;
            font-size: 11pt;
            line-height: 1.4;
            color: #000;
            position: relative;
        }
        /* Watermark */
        body::after {
            content: "NCS Management Information System (MIS)";
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 28pt;
            font-weight: bold;
            color: #228B22; /* Forest Green color */
            opacity: 0.25;
            z-index: -1;
            pointer-events: none;
            white-space: nowrap;
            font-family: 'Times New Roman', serif;
            display: block;
            width: 80%;
            max-width: 80%;
            text-align: center;
        }
        @media print {
            body::after {
                opacity: 0.20;
                z-index: -1;
                font-size: 24pt;
                width: 70%;
                max-width: 70%;
            }
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 16pt;
            font-weight: bold;
            margin: 5px 0;
        }
        .header h2 {
            font-size: 14pt;
            font-weight: bold;
            margin: 5px 0;
        }
        .report-info {
            margin: 15px 0;
            text-align: right;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th {
            background-color: #f0f0f0;
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            font-size: 10pt;
        }
        td {
            border: 1px solid #000;
            padding: 6px;
            font-size: 10pt;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 9pt;
        }
        @media print {
            body {
                margin: 0;
                padding: 0;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print" style="text-align: center; margin-bottom: 20px; padding: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background: #007bff; color: white; border: none; border-radius: 5px;">
            Print Report
        </button>
    </div>

    <div class="header">
        <h1>NIGERIA CUSTOMS SERVICE</h1>
        <h2>{{ $reportTitle ?? 'REPORT' }}</h2>
    </div>

    <div class="report-info">
        <p><strong>Generated:</strong> {{ now()->format('d M Y, h:i A') }}</p>
        @if(isset($generatedBy))
        <p><strong>Generated By:</strong> {{ $generatedBy }}</p>
        @endif
    </div>

    @if(isset($filters) && count($filters) > 0)
    <div style="margin: 15px 0;">
        <strong>Filters:</strong>
        <ul>
            @foreach($filters as $key => $value)
            <li><strong>{{ ucfirst(str_replace('_', ' ', $key)) }}:</strong> {{ $value }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <table>
        <thead>
            <tr>
                @foreach($columns as $column)
                <th>{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @if(count($data) > 0)
                @foreach($data as $row)
                <tr>
                    @foreach($columns as $column)
                    <td>{{ $row[$column['key']] ?? 'N/A' }}</td>
                    @endforeach
                </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align: center; padding: 20px;">
                        No data available
                    </td>
                </tr>
            @endif
        </tbody>
    </table>

    @if(isset($summary))
    <div style="margin-top: 20px;">
        <strong>Summary:</strong>
        <ul>
            @foreach($summary as $key => $value)
            <li><strong>{{ ucfirst(str_replace('_', ' ', $key)) }}:</strong> {{ $value }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="footer">
        <p>Page 1 of 1</p>
        <p>Generated by NCS Employee Portal System</p>
    </div>
</body>
</html>

