<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quarantine / Expired Stock Report - Print</title>
    <style>
        @page {
            size: A4;
            margin: 20mm;
        }
        body {
            font-family: 'Times New Roman', serif;
            font-size: 11pt;
            line-height: 1.4;
            color: #000;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 16pt;
            font-weight: bold;
            margin: 5px 0;
        }
        .header h2 {
            font-size: 14pt;
            font-weight: bold;
            margin: 5px 0;
        }
        .report-info {
            margin: 15px 0;
            text-align: right;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th {
            background-color: #f0f0f0;
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            font-size: 10pt;
        }
        td {
            border: 1px solid #000;
            padding: 6px;
            font-size: 10pt;
        }
        .text-center {
            text-align: center;
        }
        .font-bold {
            font-weight: bold;
        }
        .restricted {
            text-align: center;
            font-weight: bold;
            font-size: 11pt;
            margin: 5px 0;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 9pt;
        }
        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print" style="text-align: center; margin-bottom: 20px; padding: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background: #007bff; color: white; border: none; border-radius: 5px;">
            Print Report
        </button>
        <button onclick="window.close()" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background: #6c757d; color: white; border: none; border-radius: 5px; margin-left: 10px;">
            Close
        </button>
    </div>

    <div class="restricted">RESTRICTED</div>

    <div class="header">
        <h1>NIGERIA CUSTOMS SERVICE</h1>
        <h2>QUARANTINE / EXPIRED STOCK REPORT</h2>
        <p style="margin-top: 5px; font-size: 12pt;">
            Status: {{ $status ?: 'All Statuses' }}
            @if($locationType)
                | Location: {{ $locationType === 'CENTRAL_STORE' ? 'Central Medical Store' : 'Command Pharmacies' }}
            @endif
            @if($command)
                - {{ $command->name }}
            @endif
        </p>
    </div>

    <div class="report-info">
        <p><strong>Generated:</strong> {{ now()->format('d M Y, h:i A') }}</p>
        <p><strong>Generated By:</strong> {{ $generatedBy }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Drug Name</th>
                <th style="width: 15%;">Location</th>
                <th style="width: 10%;">Batch</th>
                <th style="width: 10%;">Quantity</th>
                <th style="width: 12%;">Expiry Date</th>
                <th style="width: 8%;">Status</th>
                <th style="width: 15%;">Action Notes</th>
            </tr>
        </thead>
        <tbody>
            @php $sn = 1; @endphp
            @forelse($records as $record)
                <tr>
                    <td>{{ $sn++ }}</td>
                    <td>{{ $record->drug->name ?? 'Unknown' }}</td>
                    <td>
                        @if($record->location_type === 'CENTRAL_STORE')
                            Central Store
                        @else
                            {{ $record->command->name ?? 'Command' }}
                        @endif
                    </td>
                    <td>{{ $record->batch_number ?? '-' }}</td>
                    <td class="text-center">{{ number_format($record->quantity) }}</td>
                    <td>{{ $record->expiry_date->format('d M Y') }}</td>
                    <td class="text-center font-bold">{{ $record->status }}</td>
                    <td>
                        {{ $record->action_notes ?: '-' }}
                        @if($record->acted_by)
                            <br><small>By: {{ $record->actedBy->officer->full_name ?? 'System' }}</small>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="text-center" style="padding: 20px;">No records found matching criteria</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div style="margin-top: 20px; border-top: 1px solid #000; padding-top: 10px;">
        <p><strong>Summary:</strong></p>
        <ul style="list-style-type: none; padding-left: 0;">
            <li>Total Records in Report: {{ $records->count() }}</li>
            <li>Total Quantity: {{ number_format($records->sum('quantity')) }} units</li>
        </ul>
    </div>

    <div class="footer">
        <p>Generated by NCS Employee Portal - Pharmacy Management System</p>
    </div>
</body>
</html>
